### ISSUE TITLE
writeInProgress sequencing?

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-couchbase#148]
In the Cassandra plugin we have `writeInProgress` with the description:
"readHighestSequence must be performed after pending write for a persistenceId when the persistent actor is restarted."

https://github.com/akka/akka-persistence-cassandra/blob/master/core/src/main/scala/akka/persistence/cassandra/journal/CassandraJournal.scala#L67

Do we need that here too?

**Comment by patriknw** [comment]
Also take a look at `pendingDeletes`: https://github.com/akka/akka-persistence-cassandra/blob/master/core/src/main/scala/akka/persistence/cassandra/journal/CassandraJournal.scala#L72

**Comment by johanandren** [comment]
Ah, good point, yes I think we will need that.

**Comment by johanandren** [comment]
Deletes in progress we don't need since that is a simple metadata update and doesn't touch the actual events, but the `writeInProgress` I'll add.
