### ISSUE TITLE
PR the connector to Alpakka

### ISSUE THREAD

**Issue by johanandren** [akka/akka-persistence-couchbase#149]
And make it an external thing we depend on instead of a part of this project

**Comment by johanandren** [comment]
@chbatey @patriknw @ennru I wonder on what schedule we should do this, it would have been nice to have in the first non milestone but there's no time for that, so we PR the connector in parallell with having it in a 1.0 and then switch over to using that in a later release?

**Comment by johanandren** [comment]
Discussed this with Enno a bit, and we'll try to PR the connector back to Alpakka next week, but keep our own version of it for the release to avoid having to depend on a new Alpakka release.

**Comment by ennru** [comment]
Fixed with #192
