### ISSUE TITLE
Extra safety measure against missing events on replay

### ISSUE THREAD

**Issue by johanandren** [akka/akka-persistence-couchbase#152]
Since the indexes are eventually consistent it is theoretically possible that when a persistent actor is stopped on one node and started on another one the new one does not see the last written event. This is very unlikely to actually happen since stopping-starting-handing-over with sharding for example will always take some time, however it would be good if we could detect and fail _if_ this would happen.

Proposed solution: when we have read all events, do a get for the next sequence number and fail the replay if it is there.

**Comment by chbatey** [comment]
I guess we can do this on the read highest sequence nr than the replay of messages
