### ISSUE TITLE
Failed: Whitesource

### ISSUE THREAD

**Issue by chbatey** [akka/akka-persistence-couchbase#158]
The latest Lagom RC has broken Whitresource for bringing in:

```
[error] java.lang.RuntimeException: Some dependencies were rejected by the organization's policies:
[error] akka-persistence-couchbase-master:
[error] * javax.activation-api-1.2.0.jar (rejected by policy '*GPL* - Reject')
```

Guess that should be provided

**Comment by chbatey** [comment]
Talking to the play team this is a false positive as it is duel licenced with CDDL

**Comment by johanandren** [comment]
So we can mark that in whitesource somehow? Do we really need the dependency or could we just exclude it instead?
