### ISSUE TITLE
Watching of persistent actors doesn't work

### ISSUE THREAD

**Issue by chbatey** [akka/akka-persistence-couchbase#169]
`asyncReplayMessages` is not called on the actor thread so we can't get the persistent actor with `sender()`. Also replay is not always called. E.g. on the first time the persistenceId exists and if there is a current snapshot.

We need to do it in `asyncReadHighestSequenceNr` which is called on the journal thread when receiving a message from `Eventsourced`

**Comment by chbatey** [comment]
Related: https://github.com/akka/akka/issues/25970 which would avoid the guess work for when a persistent actor starts

**Comment by chbatey** [comment]
Ah should have added to project, sorry

**Comment by johanandren** [comment]
Apology accepted
