### ISSUE TITLE
Prefer x.y.z version names

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-persistence-couchbase#211]
Prior to 1.0.0, it is common in the Akka ecosystem to use `0.x` versions.

We should converge to `x.y.z` after `1.0.0

**Comment by patriknw** [comment]
I agree, it should be 1.0.x. Let’s fix for 1.0.1

**Comment by johanandren** [comment]
Ah, sorry, I didn't think about this sine we started out with a two digit version.

**Comment by ennru** [comment]
This uses the major.minor.patch scheme now.
