### ISSUE TITLE
Clarify that it can be used with Akka 2.6.x

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-couchbase#238]
Clarify in dependency section: https://doc.akka.io/docs/akka-persistence-couchbase/current/overview.html#project-info

Also mention that transitive Akka dependencies, such as akka-persistence-query might need explicit declaration in the application's build.

**Comment by ennru** [comment]
What about the persistence testkit use of Scalatest 3.1 in Akka 2.6?

**Comment by patriknw** [comment]
That is persistence-tck, and that doesn’t matter for end users.

**Comment by patriknw** [comment]
something like https://doc.akka.io/docs/akka-persistence-cassandra/current/overview.html#dependencies

**Comment by ennru** [comment]
Fixed with #240
