### ISSUE TITLE
Lagom CouchbaseSession

### ISSUE THREAD

**Issue by ygree** [akka/akka-persistence-couchbase#58]
Analog `com.lightbend.lagom.javadsl.persistence.cassandra.CassandraSession`

- [x] CouchbaseSession for scaladsl
- [x] CouchbaseSession for javadsl

**Comment by johanandren** [comment]
I'm thinking we can just use the session I started on in the client, rather that introducing an additional one, still missing Java API though, I think we should wait with the Java API until we know what should be in there on the Scala side.

**Comment by ygree** [comment]
In any case it can wait, because it's only required for read-side implementation.

**Comment by johanandren** [comment]
Id this also a duplicate for #28 ?

**Comment by patriknw** [comment]
Yes, shouldn't be needed. The original reason for adding CassandraSession to Lagom was that we didn't have a public API (that was good enough) at that time.
