### ISSUE TITLE
Order for event by tag that scales

### ISSUE THREAD

**Issue by johanandren** [akka/akka-persistence-couchbase#66]
The previous impl used a counter which will, when configured with persistTo > 0 or replicateTo > 0 fail concurrent requests. One idea is timestamps which will work as long as there isn't clock skew.

**Comment by patriknw** [comment]
Well, then it should be something like Cassandra's time based UUID, see `com.datastax.driver.core.utils.UUIDs`.

(a temporary workaround could be to use System.currentTimeMillis)
