### ISSUE TITLE
Plugin Dispatcher

### ISSUE THREAD

**Issue by ygree** [akka/akka-persistence-couchbase#98]
Currently we don't use `plugin-dispatcher` setting. All Couchbase IO is running by RxJava's executor.
All trivial result transformations are done either in the same thread `.map(_ => ())(ExecutionContexts.sameThreadExecutionContext)` or with `context.dispatcher` see `CouchbaseJournal`. Do we need to make it configurable or these defaults are okay?
If we stay with this default we don't need `couchbase-journal.read.plugin-dispatcher` setting.

Also we could use a configurable Execution Context to run all Couchbase IO as opposed to the Couchbase RxJava Scheduler. It will require implement an adapter for RxJava Scheduler (for instance: https://github.com/ReactiveX/RxScala/pull/91/files) and passing it explicitly to `subscribeOn` method.

**Comment by johanandren** [comment]
The reason why we want to run on a separate dispatcher is if there is some surprising blocking going on. I think we can leave the RxJava stuff on the default unless we can come up with good motivation not to do so. 

Trivial transformations on same thread is an optimization to avoid an extra thread pool scheduling for things that does not take any time and will never fail, so those we'll want to keep.

**Comment by johanandren** [comment]
Note that even if we don't explicitly use that setting it is used by the Akka persistence infra to decide what dispatcher to run the plugin actor(s) on.

**Comment by patriknw** [comment]
> used by the Akka persistence infra to decide what dispatcher to run the plugin actor(s) on

and therefore it's great that you use the `context.dispatcher` for everything (and sameThreadExecutionContext is also fine if it's trivial transformation that is guaranteed to know throw)

**Comment by ygree** [comment]
> Note that even if we don't explicitly use that setting it is used by the Akka persistence infra to decide what dispatcher to run the plugin actor(s) on.

Interesting. I see the usages in `akka-persistence`. Thanks, Johan! I'll add the description to be explicit about it.
